version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web-app:
    stdin_open: true
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: nextjs-web-app-demo
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  backend-app:
    stdin_open: true
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-web-app-api-demo
    env_file:
      - backend/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    restart: always

volumes:
  postgres-data:
  pgadmin-data:

